window.word = [
  {
    "WordList": {
      "インタープリタ": "解释器", 
      "インデックス": "index", 
      "インデント": "缩进", 
      "オブジェクト": "object", 
      "コマンド": "command", 
      "コマンドライン引数": "命令行参数", 
      "リダイレクト": "redirect，重定向", 
      "パッケージ": "package", 
      "ルトインモジュール": "Built-in Modules", 
      "標準ライブラリ": "标准库", 
      "スクリプト": "script", 
      "エラー": "error", 
      "カッコ": "括号", 
      "カレントディレクトリ": "当前目录", 
      "グローバルスコープ": "Global Scope", 
      "デフォルト": "default", 
      "ディクショナリ": "dict", 
      "タプル": "tuples，元组", 
      "バックスラッシュ": "反斜杠", 
      "ブール": "布尔",
      "シンボリックリンク": "符号链接，软链接", 
      "ディレクトリ": "directory，目录", 
      "ユーザーディレクトリ": "user directory", 
      "仮想環境": "虚拟环境", 
      "引数の受け渡し": "传递参数", 
      "アンダーバー": "_", 
      "シャープ": "# 【Sharp】", 
      "ハイフン": "- 【连字符】", 
      "ハンドラ": "处理程序",
      "ハット": "^",
      "べき乗": "幂运算",
      "マルチスレッディング": "多线程"
    },
    "Unit": 1
  },
  {
    "WordList": {
      "エンコーディング": "encoding",
      "カラム": "column",
      "グリッドサーチ": "Grid Search",
      "サーバサイド": "Server Side",
      "デファクトスタンダード": "De facto standard",
      "ノード": "node",
      "ハイパーパラメータ": "hyperparameters",
      "フレーム": "框架",
      "フロントエンド": "Front end，前端",
      "ブラウザ": "browser",
    },
    "Unit": 2
  },
  {
    "WordList": {
      "アイディア": "idea",
      "アジャイルモデル": "敏捷模型",
      "アクセス": "access",
      "アクセシビリティ": "accessibility",
      "アドレス": "address",
      "アノテーション": "annotation",
      "アルゴリズム": "algorithm",
      "イメージスキャナー": "Image Scanner",
      "インストール": "install",
      "インタフェース": "interface",
      "ウォーターフォールモデル": "瀑布模型",
      "オペレーター": "操作员",
      "ガイドライン": "guidelines",
      "クラウドサービス": "Cloud Services",
      "グラフ": "graph",
      "コスト": "cost",
      "コンピュータ": "computer",
      "コールセンター": "Call Center",
      "クリティカルパス": "关键路径",
      "グループ": "group",
      "コーポレートガバナンス": "Corporate Governance",
      "サイト": "site",
      "サムネイル": "thumbnail，缩略图",
      "サーバ": "server",
      "サービス": "service",
      "サービスデスク": "服务台",
      "サービスマネジメント": "Service Management",
      "サービスマーク": "Service Mark",
      "サービスレベル": "Service Level",
      "スキル": "skill",
      "ソースプログラム": "源程序",
      "システム": "system",
      "スケジュール": "schedule",
      "スコープ": "scope",
      "スマートファクトリー": "Smart Factory",
      "セキュリティ": "安全",
      "セキュリティパッチ": "安全补丁",
      "セキュリティマネジメントシステム": "Security Management System",
      "セル": "cell",
      "ゼロデイ": "零日漏洞",
      "ソフトウェア": "software",
      "ソフトウェアライフサイクル": "Software Life Cycle",
      "ソリューション": "solution",
      "テキストデータ": "text data",
      "デザイン": "design",
      "デザインルール": "design rule",
      "デジタル": "digital",
      "デジタルフォレンジックス": "Digital Forensics，数字取证",
      "デバイス": "device",
      "データ": "data",
      "データベース": "Data Science",
      "チャットボット": "chatbots",
      "ネットワーク": "network",
      "ツール": "tool",
      "トランザクション": "transaction，交易",
      "トレーニング": "training",
      "メール": "mail",
      "メールサーバ": "Mail Server",
      "ハードウェア": "hardware",
      "ハッカソン": "黑客马拉松",
      "パケット": "packet",
      "パターン": "pattern",
      "パフォーマンス": "performance",
      "パーセント": "%",
      "バイオメトリクス": "生物识别技术",
      "バイアス": "bias",
      "パスワード": "密码",
      "パネル": "panel，控制板",
      "バリュー": "value",
      "ビジョン": "vision",
      "ビジネスモデル": "Business Model",
      "フレキシブル": "flexible",
      "ファインチューニング": "fine tuning",
      "フェーズ": "phase",
      "プラチナバンド": "白金乐队",
      "ブルートフォース": "Brute force，暴力破解",
      "プレシデンスダイアグラム": "优先图",
      "プロトコル": "protocol, 协议",
      "プロキシサーバ": "Proxy Server",
      "ブログ": "blog",
      "プログラム": "program",
      "プロジェクト": "project",
      "プロセス": "process",
      "プロセスマイニング": "Process Mining",
      "ブロックチェーン": "区块链",
      "ベンダー": "供应商，卖方",
      "ポイント": "point",
      "ホスト": "ホスト",
      "ホームページ": "Home page",
      "マニュアル": "manual",
      "マルウェア": "恶意软件",
      "マーケティング": "营销",
      "メモリ": "memory",
      "メッセージ": "message",
      "ミッション": "mission",
      "モデル": "model",
      "ランサムウェア": "ransomware，勒索软件",
      "リスク": "risk",
      "リスクマネジメント": "Risk Management",
      "リスト": "list",
      "ルール": "rule",
      "レベル": "level",
      "ログイン": "log in",
      "ワークシート": "worksheet"
    },
    "Unit": 3
  },
  {
    "WordList": {
      "エプロンセット": "围裙套装",
      "都合": "方便",
      "お嫁さん": "新娘",
      "旦那さん": "丈夫",
      "チームの奴ら": "The team guys",
      "商売女": "妓女",
      "嫁ごっこ": "扮演新娘",
      "目隠し": "眼罩",
      "鳥肌": "鸡皮疙瘩",
      "落書": "涂鸦",
      "スポブラ": "运动胸罩",
      "レギンス": "绑腿",
      "バケツ": "桶",
      "絆創膏": "绷带"
    },
    "Unit": 4
  }
]
